"""
Список брендів авто для розпізнавання в тексті оголошення.
Відсортований так, щоб довші/складніші назви (Mercedes-Benz, Land Rover)
перевірялись раніше за короткі (Mercedes, Land), щоб уникнути хибних збігів.
Пишемо у нижньому регістрі - порівняння теж буде case-insensitive.
"""

CAR_BRANDS = [
    "mercedes-benz", "mercedes benz", "mercedes", "mersedes", "мерседес",
    "land rover", "range rover", "ленд ровер", "рендж ровер",
    "volkswagen", "vw", "фольксваген", "фольксваген", "вольксваген",
    "bmw", "бмв",
    "audi", "ауді", "ауди",
    "toyota", "тойота",
    "lexus", "лексус",
    "skoda", "škoda", "шкода",
    "renault", "рено",
    "peugeot", "пежо",
    "citroen", "citroën", "ситроен",
    "opel", "опель",
    "ford", "форд",
    "chevrolet", "шевроле",
    "hyundai", "хюндай", "хендай", "хюндай",
    "kia", "кіа", "киа",
    "nissan", "ніссан", "ниссан",
    "mazda", "мазда",
    "mitsubishi", "мітсубісі", "мицубиси",
    "subaru", "субару",
    "honda", "хонда",
    "suzuki", "сузукі", "сузуки",
    "volvo", "вольво",
    "jeep", "джип",
    "chrysler", "крайслер",
    "dodge", "додж",
    "cadillac", "кадиллак",
    "gmc",
    "lincoln", "линкольн",
    "tesla", "тесла",
    "porsche", "порше",
    "jaguar", "ягуар",
    "mini", "міні",
    "fiat", "фіат", "фиат",
    "alfa romeo", "альфа ромео",
    "seat", "сеат",
    "dacia", "дачія", "дачия",
    "infiniti", "инфинити",
    "acura", "акура",
    "buick", "бьюик",
    "lada", "ваз", "лада",
    "daewoo", "деу",
    "ssangyong", "санг йонг", "сангйонг",
    "geely", "джили",
    "chery", "чери",
    "haval", "хавал",
    "byd",
    "great wall", "грейт волл",
    "man", "ман",
    "scania", "скания", "сканія",
    "iveco", "ивеко", "івеко",
    "daf", "даф",
    "volvo truck",
    "renault trucks",
]

# для нормалізації бренду до "канонічного" вигляду при виводі користувачу
BRAND_CANONICAL = {
    "mersedes": "Mercedes-Benz", "мерседес": "Mercedes-Benz",
    "mercedes benz": "Mercedes-Benz", "mercedes-benz": "Mercedes-Benz", "mercedes": "Mercedes-Benz",
    "ленд ровер": "Land Rover", "land rover": "Land Rover",
    "рендж ровер": "Range Rover", "range rover": "Range Rover",
    "vw": "Volkswagen", "фольксваген": "Volkswagen", "вольксваген": "Volkswagen", "volkswagen": "Volkswagen",
    "бмв": "BMW", "bmw": "BMW",
    "ауді": "Audi", "ауди": "Audi", "audi": "Audi",
    "тойота": "Toyota", "toyota": "Toyota",
    "лексус": "Lexus", "lexus": "Lexus",
    "škoda": "Skoda", "шкода": "Skoda", "skoda": "Skoda",
    "рено": "Renault", "renault": "Renault",
    "пежо": "Peugeot", "peugeot": "Peugeot",
    "citroën": "Citroen", "ситроен": "Citroen", "citroen": "Citroen",
    "опель": "Opel", "opel": "Opel",
    "форд": "Ford", "ford": "Ford",
    "шевроле": "Chevrolet", "chevrolet": "Chevrolet",
    "хюндай": "Hyundai", "хендай": "Hyundai", "hyundai": "Hyundai",
    "кіа": "Kia", "киа": "Kia", "kia": "Kia",
    "ніссан": "Nissan", "ниссан": "Nissan", "nissan": "Nissan",
    "мазда": "Mazda", "mazda": "Mazda",
    "мітсубісі": "Mitsubishi", "мицубиси": "Mitsubishi", "mitsubishi": "Mitsubishi",
    "субару": "Subaru", "subaru": "Subaru",
    "хонда": "Honda", "honda": "Honda",
    "сузукі": "Suzuki", "сузуки": "Suzuki", "suzuki": "Suzuki",
    "вольво": "Volvo", "volvo": "Volvo",
    "джип": "Jeep", "jeep": "Jeep",
    "крайслер": "Chrysler", "chrysler": "Chrysler",
    "додж": "Dodge", "dodge": "Dodge",
    "кадиллак": "Cadillac", "cadillac": "Cadillac",
    "линкольн": "Lincoln", "lincoln": "Lincoln",
    "тесла": "Tesla", "tesla": "Tesla",
    "порше": "Porsche", "porsche": "Porsche",
    "ягуар": "Jaguar", "jaguar": "Jaguar",
    "міні": "Mini", "mini": "Mini",
    "фіат": "Fiat", "фиат": "Fiat", "fiat": "Fiat",
    "альфа ромео": "Alfa Romeo", "alfa romeo": "Alfa Romeo",
    "сеат": "Seat", "seat": "Seat",
    "дачія": "Dacia", "дачия": "Dacia", "dacia": "Dacia",
    "инфинити": "Infiniti", "infiniti": "Infiniti",
    "акура": "Acura", "acura": "Acura",
    "бьюик": "Buick", "buick": "Buick",
    "ваз": "Lada", "лада": "Lada", "lada": "Lada",
    "деу": "Daewoo", "daewoo": "Daewoo",
    "санг йонг": "SsangYong", "сангйонг": "SsangYong", "ssangyong": "SsangYong",
    "джили": "Geely", "geely": "Geely",
    "чери": "Chery", "chery": "Chery",
    "хавал": "Haval", "haval": "Haval",
    "byd": "BYD",
    "грейт волл": "Great Wall", "great wall": "Great Wall",
    "ман": "MAN", "man": "MAN",
    "сканія": "Scania", "скания": "Scania", "scania": "Scania",
    "івеко": "Iveco", "ивеко": "Iveco", "iveco": "Iveco",
    "даф": "DAF", "daf": "DAF",
    "gmc": "GMC",
    "audi": "Audi",
}