"""
Список брендів авто для розпізнавання в тексті оголошення.
Відсортований так, щоб довші/складніші назви (Mercedes-Benz, Land Rover)
перевірялись раніше за короткі (Mercedes, Land), щоб уникнути хибних збігів.
Пишемо у нижньому регістрі - порівняння теж буде case-insensitive.
"""

CAR_BRANDS = [
    "mercedes-benz", "mercedes benz", "mercedes", "mersedes", "мерседес",
    "land rover", "range rover", "ленд ровер", "рендж ровер",
    "discovery", "дискавері", "дискавери",  # Land Rover Discovery без явної назви бренду
    "countryman", "кантрімен", "кантримен",  # Mini Countryman без «Mini»
    "clubman", "клабмен",
    "paceman", "пейсмен",
    "golf", "гольф",  # VW Golf без «Volkswagen»
    "volkswagen", "vw", "фольксваген", "фольксваген", "вольксваген",
    "bmw", "бмв",
    "audi", "ауді", "ауди",
    "prado", "прадо",  # Toyota Land Cruiser Prado без явної назви бренду
    "toyota", "тойота",
    "lexus", "лексус",
    "skoda", "škoda", "шкода",
    "renault", "рено",
    "peugeot", "пежо",
    "citroen", "citroën", "ситроен",
    "opel", "опель",
    "ford", "форд",
    "chevrolet", "шевроле",
    "hyundai", "хюндай", "хендай", "хюндай",
    "kia", "кіа", "киа",
    "nissan", "ніссан", "ниссан",
    "mazda", "мазда",
    "pajero", "паджеро",  # Mitsubishi Pajero без явної назви бренду
    "mitsubishi", "мітсубісі", "мицубиси",
    "subaru", "субару",
    "honda", "хонда",
    "suzuki", "сузукі", "сузуки",
    "volvo", "вольво",
    "wrangler", "вранглер",  # Jeep Wrangler без явної назви бренду
    "jeep", "джип",
    "hummer", "хаммер", "хамер",
    "chrysler", "крайслер",
    "dodge", "додж",
    "cadillac", "кадиллак",
    "gmc",
    "lincoln", "линкольн",
    "tesla", "тесла",
    "porsche", "порше",
    "jaguar", "ягуар",
    "mini", "міні",
    "fiat", "фіат", "фиат",
    "alfa romeo", "альфа ромео",
    "seat", "сеат",
    "dacia", "дачія", "дачия",
    "infiniti", "инфинити",
    "acura", "акура",
    "buick", "бьюик",
    "lada", "ваз", "лада",
    "daewoo", "деу",
    "ssangyong", "санг йонг", "сангйонг",
    "geely", "джили",
    "chery", "чери",
    "haval", "хавал",
    "byd",
    "zeekr", "зікр", "зикр", "зеекр",
    "nio",
    "xpeng", "x peng",
    "jaecoo", "джику",
    "omoda", "омода",
    "jetour", "джетур",
    "changan", "чанган",
    "dongfeng",
    "voyah", "воя",
    "skywell",
    "great wall", "gwm", "грейт волл",
    "genesis", "дженesis",
    "polestar", "полстар",
    "cupra", "купра",
    "li auto", "li-auto", "lixiang", "ли авто",
    "mg", "эмджи",
    "ram", "рам",
    "bentley", "бентли", "бентлі",
    "maserati", "мазерати",
    "lamborghini", "ламборгини",
    "mclaren", "макларен",
    "lotus", "лотус",
    "lucid", "rivian", "vinfast", "exeed", "hongqi", "leapmotor",
    "ora", "tank", "aito", "avatr", "deepal", "seres", "foton", "gac", "baic",
    "xiaomi", "сяомі", "huawei", "хуавей", "denza", "денза", "yangwang", "янван",
    "lynk & co", "lynk and co", "lynk&co",
    "man", "ман",
    "scania", "скания", "сканія",
    "iveco", "ивеко", "івеко",
    "daf", "даф",
    "volvo truck",
    "renault trucks",
    # Додаткові марки з FE-каталогу (були лише в BRAND_CANONICAL)
    "aston martin", "астон мартин",
    "ravon", "равон",
    "saab", "сааб",
    "smart", "смарт",
    "lancia", "ланча",
    "rover", "ровер",
    "ds automobiles", "ds",
    "isuzu", "isuzu",
    "samsung", "samsung",
    "proton", "proton",
    # Моделі без явної марки (MODEL_AS_BRAND + пошук у тексті)
    "touareg", "туарег",
    "qashqai", "кашкай", "кашкаї",
    "tiguan", "тигуан",
    "octavia", "октавія", "октавия",
    "macan", "макан",
    "cayenne", "каен", "кайен",
    "kangoo", "кангу",
    "transit", "транзит",
]

# Ключ = альтернативна назва (alias), значення = (canonical_brand, model_name).
# Коли extractor знаходить такий ключ, бренд береться звідси, а MODEL_NAME
# використовується як початок моделі (а не наступне слово після ключа).
MODEL_AS_BRAND: dict[str, tuple[str, str]] = {
    "discovery": ("Land Rover", "Discovery"),
    "дискавері": ("Land Rover", "Discovery"),
    "дискавери": ("Land Rover", "Discovery"),
    "prado": ("Toyota", "Land Cruiser Prado"),
    "прадо": ("Toyota", "Land Cruiser Prado"),
    "pajero": ("Mitsubishi", "Pajero"),
    "паджеро": ("Mitsubishi", "Pajero"),
    "wrangler": ("Jeep", "Wrangler"),
    "вранглер": ("Jeep", "Wrangler"),
    # Mini: часто пишуть лише модель без «Mini»; «cooper» не додаємо —
    # занадто багато хибних «Cooper Centre».
    "countryman": ("Mini", "Countryman"),
    "кантрімен": ("Mini", "Countryman"),
    "кантримен": ("Mini", "Countryman"),
    "clubman": ("Mini", "Clubman"),
    "клабмен": ("Mini", "Clubman"),
    "paceman": ("Mini", "Paceman"),
    "пейсмен": ("Mini", "Paceman"),
    "golf": ("Volkswagen", "Golf"),
    "гольф": ("Volkswagen", "Golf"),
    "touareg": ("Volkswagen", "Touareg"),
    "туарег": ("Volkswagen", "Touareg"),
    "tiguan": ("Volkswagen", "Tiguan"),
    "тигуан": ("Volkswagen", "Tiguan"),
    "qashqai": ("Nissan", "Qashqai"),
    "кашкай": ("Nissan", "Qashqai"),
    "кашкаї": ("Nissan", "Qashqai"),
    "octavia": ("Skoda", "Octavia"),
    "октавія": ("Skoda", "Octavia"),
    "октавия": ("Skoda", "Octavia"),
    "macan": ("Porsche", "Macan"),
    "макан": ("Porsche", "Macan"),
    "cayenne": ("Porsche", "Cayenne"),
    "каен": ("Porsche", "Cayenne"),
    "кайен": ("Porsche", "Cayenne"),
    "kangoo": ("Renault", "Kangoo"),
    "кангу": ("Renault", "Kangoo"),
    "transit": ("Ford", "Transit"),
    "транзит": ("Ford", "Transit"),
}

# для нормалізації бренду до "канонічного" вигляду при виводі користувачу
BRAND_CANONICAL = {
    "mersedes": "Mercedes-Benz", "мерседес": "Mercedes-Benz",
    "mercedes benz": "Mercedes-Benz", "mercedes-benz": "Mercedes-Benz", "mercedes": "Mercedes-Benz",
    "ленд ровер": "Land Rover", "land rover": "Land Rover",
    "discovery": "Land Rover", "дискавері": "Land Rover", "дискавери": "Land Rover",
    "рендж ровер": "Range Rover", "range rover": "Range Rover",
    "vw": "Volkswagen", "фольксваген": "Volkswagen", "вольксваген": "Volkswagen", "volkswagen": "Volkswagen",
    "golf": "Volkswagen", "гольф": "Volkswagen",
    "бмв": "BMW", "bmw": "BMW",
    "ауді": "Audi", "ауди": "Audi", "audi": "Audi",
    "тойота": "Toyota", "toyota": "Toyota",
    "prado": "Toyota", "прадо": "Toyota",
    "лексус": "Lexus", "lexus": "Lexus",
    "škoda": "Skoda", "шкода": "Skoda", "skoda": "Skoda",
    "рено": "Renault", "renault": "Renault",
    "пежо": "Peugeot", "peugeot": "Peugeot",
    "citroën": "Citroen", "ситроен": "Citroen", "citroen": "Citroen",
    "опель": "Opel", "opel": "Opel",
    "форд": "Ford", "ford": "Ford",
    "шевроле": "Chevrolet", "chevrolet": "Chevrolet",
    "хюндай": "Hyundai", "хендай": "Hyundai", "hyundai": "Hyundai",
    "кіа": "Kia", "киа": "Kia", "kia": "Kia",
    "ніссан": "Nissan", "ниссан": "Nissan", "nissan": "Nissan",
    "мазда": "Mazda", "mazda": "Mazda",
    "мітсубісі": "Mitsubishi", "мицубиси": "Mitsubishi", "mitsubishi": "Mitsubishi",
    "pajero": "Mitsubishi", "паджеро": "Mitsubishi",
    "субару": "Subaru", "subaru": "Subaru",
    "хонда": "Honda", "honda": "Honda",
    "сузукі": "Suzuki", "сузуки": "Suzuki", "suzuki": "Suzuki",
    "вольво": "Volvo", "volvo": "Volvo",
    "джип": "Jeep", "jeep": "Jeep",
    "hummer": "Hummer", "хаммер": "Hummer", "хамер": "Hummer",
    "wrangler": "Jeep", "вранглер": "Jeep",
    "крайслер": "Chrysler", "chrysler": "Chrysler",
    "додж": "Dodge", "dodge": "Dodge",
    "кадиллак": "Cadillac", "cadillac": "Cadillac",
    "линкольн": "Lincoln", "lincoln": "Lincoln",
    "тесла": "Tesla", "tesla": "Tesla",
    "порше": "Porsche", "porsche": "Porsche",
    "ягуар": "Jaguar", "jaguar": "Jaguar",
    "міні": "Mini", "mini": "Mini",
    "countryman": "Mini", "кантрімен": "Mini", "кантримен": "Mini",
    "clubman": "Mini", "клабмен": "Mini",
    "paceman": "Mini", "пейсмен": "Mini",
    "фіат": "Fiat", "фиат": "Fiat", "fiat": "Fiat",
    "альфа ромео": "Alfa Romeo", "alfa romeo": "Alfa Romeo",
    "сеат": "Seat", "seat": "Seat",
    "дачія": "Dacia", "дачия": "Dacia", "dacia": "Dacia",
    "инфинити": "Infiniti", "infiniti": "Infiniti",
    "акура": "Acura", "acura": "Acura",
    "бьюик": "Buick", "buick": "Buick",
    "ваз": "Lada", "лада": "Lada", "lada": "Lada",
    "деу": "Daewoo", "daewoo": "Daewoo",
    "санг йонг": "SsangYong", "сангйонг": "SsangYong", "ssangyong": "SsangYong",
    "джили": "Geely", "geely": "Geely",
    "чери": "Chery", "chery": "Chery",
    "хавал": "Haval", "haval": "Haval",
    "byd": "BYD",
    "zeekr": "Zeekr", "зікр": "Zeekr", "зикр": "Zeekr", "зеекр": "Zeekr",
    "nio": "NIO",
    "xpeng": "XPeng", "x peng": "XPeng",
    "jaecoo": "Jaecoo", "джику": "Jaecoo",
    "omoda": "Omoda", "омода": "Omoda",
    "jetour": "Jetour", "джетур": "Jetour",
    "changan": "Changan", "чанган": "Changan",
    "dongfeng": "Dongfeng",
    "voyah": "Voyah", "воя": "Voyah",
    "skywell": "Skywell",
    "грейт волл": "Great Wall", "great wall": "Great Wall",
    "ман": "MAN", "man": "MAN",
    "сканія": "Scania", "скания": "Scania", "scania": "Scania",
    "івеко": "Iveco", "ивеко": "Iveco", "iveco": "Iveco",
    "даф": "DAF", "daf": "DAF",
    "gmc": "GMC",
    "genesis": "Genesis", "дженesis": "Genesis",
    "polestar": "Polestar", "полстар": "Polestar",
    "cupra": "Cupra", "купра": "Cupra",
    "li auto": "Li Auto", "li-auto": "Li Auto", "lixiang": "Li Auto", "ли авто": "Li Auto",
    "mg": "MG", "эмджи": "MG",
    "ram": "Ram", "рам": "Ram",
    "ravon": "Ravon",
    "saab": "Saab", "сааб": "Saab",
    "bentley": "Bentley", "бентли": "Bentley", "бентлі": "Bentley",
    "maserati": "Maserati", "мазерати": "Maserati",
    "lamborghini": "Lamborghini", "ламборгини": "Lamborghini",
    "mclaren": "McLaren", "макларен": "McLaren",
    "lotus": "Lotus", "лотус": "Lotus",
    "lucid": "Lucid",
    "rivian": "Rivian",
    "vinfast": "Vinfast",
    "exeed": "Exeed",
    "hongqi": "Hongqi",
    "leapmotor": "Leapmotor",
    "ora": "Ora",
    "tank": "Tank",
    "aito": "Aito",
    "avatr": "Avatr",
    "deepal": "Deepal",
    "seres": "Seres",
    "foton": "Foton",
    "gac": "GAC",
    "baic": "BAIC",
    "xiaomi": "Xiaomi", "сяомі": "Xiaomi", "сяоми": "Xiaomi",
    "huawei": "Huawei", "хуавей": "Huawei",
    "denza": "Denza", "денза": "Denza",
    "yangwang": "Yangwang", "янван": "Yangwang", "yang wang": "Yangwang",
    "lynk & co": "Lynk & Co", "lynk and co": "Lynk & Co", "lynk&co": "Lynk & Co",
    "touareg": "Volkswagen", "туарег": "Volkswagen",
    "tiguan": "Volkswagen", "тигуан": "Volkswagen",
    "qashqai": "Nissan", "кашкай": "Nissan", "кашкаї": "Nissan",
    "octavia": "Skoda", "октавія": "Skoda", "октавия": "Skoda",
    "macan": "Porsche", "макан": "Porsche",
    "cayenne": "Porsche", "каен": "Porsche", "кайен": "Porsche",
    "kangoo": "Renault", "кангу": "Renault",
    "transit": "Ford", "транзит": "Ford",
    "ravon": "Ravon", "равон": "Ravon",
    "saab": "Saab", "сааб": "Saab",
    "smart": "Smart", "смарт": "Smart",
    "lancia": "Lancia", "ланча": "Lancia",
    "rover": "Rover", "ровер": "Rover",
    "ds": "DS", "ds automobiles": "DS",
    "isuzu": "Isuzu",
    "aston martin": "Aston Martin", "астон мартин": "Aston Martin",
    "audi": "Audi",
}