/** Повний довідник марок і моделей для фільтра пошуку (як на AUTO.RIA) */
export const BRAND_MODELS: Record<string, readonly string[]> = {
  Acura: ["CL","CSX","ILX","Integra","MDX","NSX","RDX","RL","RLX","RSX","TL","TLX","TSX","ZDX"],
  Aito: ["M5","M6","M7","M8","M9"],
  "Alfa Romeo": ["145","146","147","155","156","159","164","166","4C","8C","Brera","Giulia","Giulietta","GT","GTV","MiTo","Spider","Stelvio","Tonale"],
  "Aston Martin": ["DB11","DB9","DBS","DBX","Rapide","V8 Vantage","Vantage","Virage"],
  Audi: ["100","80","90","A1","A2","A3","A4","A4 Allroad","A5","A6","A6 Allroad","A7","A8","Cabriolet","Coupe","e-tron","e-tron GT","Q2","Q3","Q4 e-tron","Q5","Q7","Q8","R8","RS Q3","RS Q8","RS3","RS4","RS5","RS6","RS7","S3","S4","S5","S6","S7","S8","SQ5","SQ7","SQ8","TT","TTS"],
  Avatr: ["06","06T","07","11","12"],
  BAIC: ["BJ40","BJ60","BJ80","EC180","EC200","EC3","EC5","EU5","EU7","EX3","EX5","U5 Plus","X35","X55","X7"],
  Bentley: ["Arnage","Azure","Bentayga","Brooklands","Continental","Continental Flying Spur","Continental GT","Flying Spur","Mulsanne"],
  BMW: ["1 Series","2 Series","2 Series Active Tourer","2 Series Gran Tourer","3 Series","3 Series GT","4 Series","5 Series","5 Series GT","6 Series","7 Series","8 Series","i3","i4","i7","i8","iX","iX1","iX3","M2","M3","M4","M5","M6","M8","X1","X2","X3","X4","X5","X6","X7","XM","Z3","Z4","Z8"],
  Buick: ["Century","Enclave","Encore","Envision","LaCrosse","LeSabre","Lucerne","Park Avenue","Regal","Rendezvous","Riviera","Skylark","Terraza","Verano"],
  BYD: ["Atto 2","Atto 3","D1","Destroyer 05","Dolphin","E2","E5","E6","E7","EV535","F0","F3","F3R","F6","F8","Flyer","Frigate 07","G3","G6","Han","Han L","King","L3","Leopard 3","Leopard 5","Leopard 7","Leopard 8","M6","Qin","Qin EV450","Qin L","Qin Plus","S6","Sea Lion 05","Sea Lion 06","Sea Lion 07","Seagull","Seal","Seal 05","Seal 06","Seal 06 GT","Seal 07","Seal U","Shark","Shark 6","Song","Song EV500","Song L","Song Max","Song Plus","Song Pro","Song Ultra EV","Summer","Tang","Tang EV600","Tang L","V3","Xia","Yuan","Yuan EV360","Yuan Plus","Yuan Pro","Yuan Up"],
  Cadillac: ["ATS","BLS","CT4","CT5","CT6","CTS","DeVille","DTS","Escalade","Escalade ESV","Fleetwood","SRX","STS","XT4","XT5","XT6","XTS"],
  Changan: ["Alsvin","CS35","CS35 Plus","CS55","CS55 Plus","CS75","CS85","CS95","Eado","Hunter","Lamore","Qiyuan A07","Qiyuan Q05","UNI-K","UNI-T","UNI-V","UNI-Z"],
  Chery: ["Amulet","Arrizo 5","Arrizo 7","Arrizo 8","Bonus","CrossEastar","E5","Fora","Kimo","M11","QQ","Tiggo","Tiggo 2","Tiggo 2 Pro","Tiggo 3","Tiggo 4","Tiggo 4 Pro","Tiggo 5","Tiggo 7","Tiggo 7 Pro","Tiggo 8","Tiggo 8 Plus","Tiggo 8 Pro","Tiggo 8 Pro Max","Tiggo 9","Very"],
  Chevrolet: ["Alero","Astro","Avalanche","Aveo","Beretta","Blazer","Bolt","Camaro","Caprice","Captiva","Cavalier","Cobalt","Colorado","Corvette","Cruze","Epica","Equinox","Evanda","Express","HHR","Impala","Lacetti","Lanos","Malibu","Matiz","Monte Carlo","Niva","Orlando","Rezzo","Silverado","Spark","Suburban","Tahoe","Tracker","TrailBlazer","Trans Sport","Traverse","Trax","Uplander","Venture","Viva","Volt"],
  Chrysler: ["200","300C","300M","Aspen","Concorde","Crossfire","Grand Voyager","LeBaron","LHS","Neon","Pacifica","PT Cruiser","Sebring","Stratus","Town & Country","Voyager"],
  Citroen: ["Ami","AX","Berlingo","C-Crosser","C-Elysee","C-Zero","C1","C2","C3","C3 Aircross","C3 Picasso","C4","C4 Aircross","C4 Cactus","C4 Picasso","C4 SpaceTourer","C5","C5 Aircross","C5 X","C6","C8","DS3","DS4","DS5","Evasion","Grand C4 Picasso","Grand C4 SpaceTourer","Jumper","Jumpy","Nemo","Saxo","SpaceTourer","Xantia","XM","Xsara","Xsara Picasso","ZX"],
  Cupra: ["Ateca","Born","Formentor","Leon","Terramar"],
  Dacia: ["1300","1310","1325","1410","Dokker","Duster","Jogger","Lodgy","Logan","Logan MCV","Logan Pick-Up","Logan Van","Pick-Up","Sandero","Sandero Stepway","Solenza","Spring","SuperNova"],
  Daewoo: ["Espero","Evanda","Kalos","Lanos","Leganza","Magnus","Matiz","Nexia","Nubira","Rezzo","Sens","Tacuma"],
  DAF: ["CF","LF","XF"],
  Deepal: ["G318","S05","S07","S09"],
  Denza: ["D9","N7","N8L","N9","X","Z9","Z9 GT"],
  Dodge: ["Avenger","Caliber","Caravan","Challenger","Charger","Dakota","Dart","Durango","Grand Caravan","Intrepid","Journey","Magnum","Neon","Nitro","Ram","Stealth","Stratus","Viper"],
  Dongfeng: ["AX7","Fengon 5","Fengon 7","Forthing T5 EVO","Nammi 01","Rich","Shine","Warrior 917"],
  DS: ["3","4","5","7","9"],
  EXEED: ["LX","RX","TXL","VX"],
  Fiat: ["124 Spider","500","500C","500L","500X","600","Albea","Barchetta","Brava","Bravo","Croma","Doblo","Ducato","Fiorino","Freemont","Fullback","Grande Punto","Idea","Linea","Marea","Multipla","Palio","Panda","Punto","Qubo","Scudo","Sedici","Seicento","Stilo","Strada","Talento","Tempra","Tipo","Ulysse","Uno"],
  Ford: ["Aerostar","B-Max","Bronco","Bronco Sport","C-Max","Capri","Cougar","Crown Victoria","EcoSport","Edge","Escape","Escort","Excursion","Expedition","Explorer","F-150","F-250","F-350","Fiesta","Flex","Focus","Fusion","Galaxy","Granada","Grand C-Max","GT","Ka","Kuga","Maverick","Mondeo","Mustang","Mustang Mach-E","Orion","Probe","Puma","Ranger","S-Max","Scorpio","Sierra","StreetKa","Taunus","Taurus","Thunderbird","Tourneo Connect","Tourneo Custom","Transit","Transit Connect","Transit Custom","Windstar"],
  Foton: ["Sauvana","Tunland","View"],
  GAC: ["Aion ES","Aion LX","Aion S","Aion V","Aion Y","Aion Y Plus","Empow","GS3","GS4","GS5","GS8","Hyptec HL","M6","M8"],
  Geely: ["Atlas","Atlas Pro","CK","Coolray","Emgrand","Emgrand 7","Emgrand EC7","Emgrand GT","Emgrand X7","Galaxy E5","Galaxy E8","Galaxy L7","GC6","Geometry A","Geometry C","Icon","MK","Monjaro","Okavango","Panda","Preface","Tugella"],
  Genesis: ["G70","G80","G90","GV60","GV70","GV80"],
  GMC: ["Acadia","Canyon","Envoy","Jimmy","Safari","Savana","Sierra","Sonoma","Terrain","Yukon","Yukon XL"],
  "Great Wall": ["Cowry","Deer","Florid","Hover","Hover H3","Hover H5","Hover H6","Hover M2","Hover M4","Pegasus","Peri","Safe","Sailor","Sing","Socool","Wingle"],
  Haval: ["Chitu","Dargo","F5","F7","F7x","H1","H2","H5","H6","H6 GT","H6 HEV","H7","H8","H9","Jolion","Jolion Pro","M6","Raptor","Third Generation H6","Xiaolong","Xiaolong Max"],
  Honda: ["Accord","Civic","Clarity","Concerto","CR-V","CR-Z","Crosstour","Element","Fit","FR-V","HR-V","Insight","Integra","Jazz","Legend","Logo","NSX","Odyssey","Pilot","Prelude","Ridgeline","S2000","Shuttle","Stream","ZR-V"],
  Hongqi: ["E-HS3","E-HS9","E-QM5","H5","H7","H9","HQ9","HS5","HS7","LS7"],
  Huawei: ["Aito M5","Aito M6","Aito M7","Aito M8","Aito M9","Luxeed R7","Seres SF5"],
  Hummer: ["H1","H2","H3"],
  Hyundai: ["Accent","Atos","Azera","Bayon","Coupe","Creta","Elantra","Equus","Galloper","Genesis","Getz","Grand Santa Fe","Grandeur","H-1","H-100","i10","i20","i30","i40","IONIQ","IONIQ 5","IONIQ 6","ix20","ix35","ix55","Kona","Lantra","Matrix","Palisade","Pony","Santa Cruz","Santa Fe","Santamo","Solaris","Sonata","Starex","Staria","Terracan","Tiburon","Trajet","Tucson","Veloster","Venue","Veracruz","XG"],
  Infiniti: ["EX","FX","G","I30","I35","JX","M","Q30","Q45","Q50","Q60","Q70","QX30","QX4","QX50","QX55","QX56","QX60","QX70","QX80"],
  Isuzu: ["Amigo","Ascender","Axiom","Campo","D-Max","Gemini","Midi","MU","MU-X","Piazza","Rodeo","Trooper","VehiCross"],
  Iveco: ["Daily","EuroCargo","Massif"],
  JAC: ["A5 Plus","J7","JS3","JS4","JS6","JS7","S3","S5","S7","T6","T8","T9"],
  Jaecoo: ["J5","J6","J7","J8"],
  Jaguar: ["E-Pace","F-Pace","F-Type","I-Pace","S-Type","X-Type","XE","XF","XJ","XJR","XJS","XK","XKR"],
  Jeep: ["Cherokee","Commander","Compass","Gladiator","Grand Cherokee","Grand Cherokee L","Grand Wagoneer","Liberty","Patriot","Renegade","Wagoneer","Wrangler"],
  Jetour: ["Dashing","T1","T2","X50","X70","X70 Coupe","X70 Plus","X70S EV","X90","X90 Plus","X95"],
  Kia: ["Avella","Besta","Cadenza","Carens","Carnival","Ceed","Cerato","Clarus","EV6","EV9","Forte","K5","K900","Magentis","Mohave","Niro","Opirus","Optima","Picanto","Pregio","Pride","ProCeed","Quoris","Ray","Rio","Sedona","Seltos","Sephia","Shuma","Sorento","Soul","Spectra","Sportage","Stinger","Stonic","Telluride","Venga","XCeed"],
  Lada: ["110","111","112","2101","2104","2105","2106","2107","2108","2109","21099","2110","2111","2112","2113","2114","2115","Granta","Kalina","Largus","Niva","Niva Legend","Priora","Vesta","XRAY"],
  Lancia: ["Dedra","Delta","Kappa","Lybra","Musa","Phedra","Thema","Thesis","Ypsilon","Zeta"],
  "Land Rover": ["Defender","Discovery","Discovery Sport","Freelander","Range Rover","Range Rover Evoque","Range Rover Sport","Range Rover Velar","Series III"],
  Leapmotor: ["B10","C10","C11","C16","T03"],
  Lexus: ["CT","ES","GS","GX","HS","IS","LC","LFA","LM","LS","LX","NX","RC","RC F","RX","RZ","SC","UX"],
  "Li Auto": ["i6","i8","L6","L7","L8","L9","Mega","One"],
  Lifan: ["320","520","620","820","Myway","Smily","Solano","X50","X60","X70"],
  Lincoln: ["Aviator","Continental","Corsair","LS","Mark LT","MKC","MKS","MKT","MKX","MKZ","Nautilus","Navigator","Town Car"],
  Lotus: ["Elise","Emira","Evora","Exige"],
  Lucid: ["Air","Gravity"],
  "Lynk & Co": ["01","02","03","05","06","08","09","Z10"],
  MAN: ["TGE","TGL","TGM","TGS","TGX"],
  Maserati: ["3200 GT","Coupe","Ghibli","GranCabrio","GranTurismo","Grecale","Levante","MC20","Quattroporte","Spyder"],
  Mazda: ["121","2","3","323","5","6","626","929","B-Series","BT-50","CX-3","CX-30","CX-5","CX-50","CX-60","CX-7","CX-9","CX-90","Demio","MPV","MX-3","MX-30","MX-5","MX-6","Premacy","Protege","RX-7","RX-8","Tribute","Xedos"],
  "Mercedes-Benz": ["190","A-Class","AMG GT","AMG GT 4-Door Coupe","B-Class","C-Class","C-Class Coupe","Cabrio","Citan","CL","CLA","CLC","CLE","CLK","CLS","Coupe","E-Class","E-Class Coupe","EQA","EQB","EQC","EQE","EQS","EQV","G-Class","GL","GLA","GLB","GLC","GLC Coupe","GLE","GLE Coupe","GLK","GLS","M-Class","Maybach S-Class","R-Class","S-Class","S-Class Coupe","SL","SLC","SLK","SLR McLaren","SLS AMG","Sprinter","V-Class","Vaneo","Viano","Vito","X-Class"],
  MG: ["3","350","4","5","5 EV","550","6","7","750","Cyberster","HS","Marvel R","TF","ZS","ZS EV","ZST"],
  Mini: ["Clubman","Cooper","Cooper S","Countryman","Coupe","One","Paceman","Roadster"],
  Mitsubishi: ["3000 GT","ASX","Carisma","Colt","Diamante","Eclipse","Eclipse Cross","Endeavor","Galant","Grandis","i-MiEV","L200","Lancer","Mirage","Montero","Montero Sport","Outlander","Outlander Sport","Pajero","Pajero Pinin","Pajero Sport","RVR","Sigma","Space Gear","Space Runner","Space Star","Space Wagon"],
  NIO: ["EC6","EC7","EL6","EL7","EL8","ES6","ES7","ES8","ET5","ET7","Firefly"],
  Nissan: ["100NX","200SX","350Z","370Z","Almera","Almera Classic","Almera Tino","Altima","Ariya","Armada","Bluebird","Cube","Frontier","GT-R","Juke","Kicks","Leaf","Maxima","Micra","Murano","Navara","Note","NP300","NV","Pathfinder","Patrol","Pixo","Primera","Pulsar","Qashqai","Quest","Rogue","Sentra","Serena","Silvia","Skyline","Sunny","Teana","Terrano","Tiida","Titan","Townstar","Versa","X-Trail","Xterra","Z"],
  Omoda: ["C5","C7","E5","S5"],
  Opel: ["Adam","Agila","Ampera","Antara","Ascona","Astra","Calibra","Campo","Cascada","Combo","Commodore","Corsa","Crossland","Crossland X","Frontera","Grandland","Grandland X","GT","Insignia","Kadett","Meriva","Mokka","Mokka X","Monterey","Monza","Movano","Omega","Rekord","Senator","Signum","Sintra","Speedster","Tigra","Vectra","Vita","Vivaro","Zafira","Zafira Life"],
  ORA: ["Good Cat","IQ","R1"],
  Peugeot: ["1007","106","107","108","2008","205","206","207","208","3008","301","305","306","307","308","4007","4008","405","406","407","408","5008","504","505","508","604","605","607","806","807","Bipper","Boxer","Expert","Partner","RCZ","Rifter","Traveller"],
  Polestar: ["1","2","3","4","5"],
  Porsche: ["718 Boxster","718 Cayman","911","918 Spyder","924","928","944","968","Boxster","Carrera GT","Cayenne","Cayman","Macan","Panamera","Taycan"],
  Ram: ["1500","2500","3500","ProMaster"],
  Ravon: ["Gentra","Matiz","Nexia R3","R2","R4"],
  Renault: ["11","12","14","15","16","17","18","19","20","21","25","30","4","5","9","Arkana","Austral","Avantime","Captur","Clio","Dokker","Duster","Espace","Express","Fluence","Fuego","Grand Espace","Grand Scenic","Kadjar","Kangoo","Koleos","Laguna","Latitude","Logan","Master","Megane","Modus","Rafale","Safrane","Scenic","Scenic Conquest","Symbol","Talisman","Trafic","Twingo","Twizy","Vel Satis","Wind","Zoe"],
  Rivian: ["R1S","R1T"],
  Rover: ["200","214","216","218","220","25","400","414","416","418","420","45","600","618","620","623","75","800","820","825","827","CityRover","Streetwise"],
  Saab: ["9-3","9-4X","9-5","9-7X","900","9000"],
  Scania: ["G-series","P-series","R-series","S-series"],
  Seat: ["Alhambra","Altea","Altea XL","Arona","Arosa","Ateca","Cordoba","Exeo","Ibiza","Inca","Leon","Malaga","Marbella","Mii","Tarraco","Terra","Toledo"],
  Seres: ["Landian E3","SF5"],
  Skoda: ["100","105","120","130","135","136","Citigo","Enyaq","Fabia","Favorit","Felicia","Forman","Kamiq","Karoq","Kodiaq","Octavia","Praktik","Rapid","Roomster","Scala","Superb","Yeti"],
  Skywell: ["007","D10","ET5","EV6","HT-i","Mini Bus"],
  Smart: ["#1","#3","Forfour","Fortwo","Roadster"],
  SsangYong: ["Actyon","Actyon Sports","Chairman","Korando","Kyron","Musso","Rexton","Rodius","Stavic","Tivoli","Torres","XLV"],
  Subaru: ["Ascent","Baja","BRZ","Crosstrek","Forester","Impreza","Justy","Legacy","Levorg","Libero","Outback","Solterra","SVX","Tribeca","WRX","XV"],
  Suzuki: ["Alto","Baleno","Celerio","Grand Vitara","Ignis","Jimny","Kizashi","Liana","Samurai","Splash","Swace","Swift","SX4","Vitara","Wagon R","XL7"],
  Tank: ["300","400","500","700"],
  Tesla: ["Cybertruck","Model 3","Model S","Model X","Model Y","Roadster"],
  Toyota: ["4Runner","Alphard","Auris","Avalon","Avensis","Avensis Verso","Aygo","bZ4X","C-HR","Camry","Carina","Celica","Corolla","Corolla Cross","Corolla Verso","Crown","FJ Cruiser","Fortuner","GR86","GT86","Highlander","Hilux","Land Cruiser","Land Cruiser Prado","Matrix","Mirai","MR2","Paseo","Picnic","Previa","Prius","Proace","RAV4","Sequoia","Sienna","Starlet","Supra","Tacoma","Tercel","Tundra","Urban Cruiser","Venza","Verso","Yaris","Yaris Cross"],
  VinFast: ["VF-8","VF-9"],
  Volkswagen: ["Amarok","Arteon","Atlas","Beetle","Bora","Caddy","Corrado","Crafter","Cross Golf","Cross Touran","Eos","Fox","Golf","Golf Alltrack","Golf GTE","Golf Plus","Golf Sportsvan","ID.3","ID.4","ID.5","ID.6","ID.7","ID.Buzz","Jetta","Lupo","Multivan","New Beetle","Passat","Passat Alltrack","Passat CC","Phaeton","Polo","Routan","Scirocco","Sharan","T-Cross","T-Roc","Taigo","Tayron","Teramont","Tiguan","Tiguan Allspace","Touareg","Touran","Transporter","Up","Vento","Virtus"],
  Volvo: ["240","340","440","460","480","740","760","850","940","960","C30","C40","C70","EX30","EX90","S40","S60","S70","S80","S90","V40","V50","V60","V70","V90","XC40","XC60","XC70","XC90"],
  Voyah: ["Dreamer","Free","Passion"],
  WEY: ["Coffee 01","Mocha","VV5","VV6","VV7"],
  Xiaomi: ["SU7","SU7 Ultra","YU7"],
  XPeng: ["G3","G3i","G6","G7","G9","P5","P7","P7i"],
  Yangwang: ["U7","U8","U9"],
  ZAZ: ["1102","1103","1105","965","966","968","Chance","Forza","Lanos","Sens","Vida"],
  Zeekr: ["001","001 FR","007","007 GT","009","7X","8X","9X","Mix","X"],
};

export const BRANDS: string[] = Object.keys(BRAND_MODELS).sort((a, b) => a.localeCompare(b, "uk"));

export function getModelsForBrand(brand: string): string[] {
  return [...(BRAND_MODELS[brand] ?? [])];
}

export function filterOptions(options: string[], query: string, limit = 80): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return options.slice(0, limit);
  return options.filter(o => o.toLowerCase().includes(q)).slice(0, limit);
}

export const TOTAL_BRANDS = 104;
export const TOTAL_MODELS = 1645;
