/** Повний довідник марок і моделей для фільтра пошуку */
export const BRAND_MODELS: Record<string, readonly string[]> = {
  Acura: ["CL","CSX","ILX","Integra","MDX","NSX","RDX","RL","RLX","RSX","TL","TLX","TSX","ZDX"],
  "Alfa Romeo": ["145","146","147","155","156","159","164","166","4C","8C","Brera","Giulia","Giulietta","GT","GTV","MiTo","Spider","Stelvio","Tonale"],
  "Aston Martin": ["DB11","DB9","DBS","DBX","Rapide","V8 Vantage","Vantage","Virage"],
  Audi: ["100","80","90","A1","A2","A3","A4","A4 Allroad","A5","A6","A6 Allroad","A7","A8","Cabriolet","Coupe","e-tron","e-tron GT","Q2","Q3","Q4 e-tron","Q5","Q7","Q8","R8","RS Q3","RS Q8","RS3","RS4","RS5","RS6","RS7","S3","S4","S5","S6","S7","S8","SQ5","SQ7","SQ8","TT","TTS"],
  BAIC: ["BJ40","BJ60","U5 Plus","X35","X55","X7"],
  Bentley: ["Arnage","Azure","Bentayga","Brooklands","Continental","Continental Flying Spur","Continental GT","Flying Spur","Mulsanne"],
  BMW: ["1 Series","2 Series","2 Series Active Tourer","2 Series Gran Tourer","3 Series","3 Series GT","4 Series","5 Series","5 Series GT","6 Series","7 Series","8 Series","i3","i4","i7","i8","iX","iX1","iX3","M2","M3","M4","M5","M6","M8","X1","X2","X3","X4","X5","X6","X7","XM","Z3","Z4","Z8"],
  Buick: ["Century","Enclave","Encore","Envision","LaCrosse","LeSabre","Lucerne","Park Avenue","Regal","Rendezvous","Riviera","Skylark","Terraza","Verano"],
  BYD: ["Atto 3","Dolphin","Han","Seal","Song Plus","Tang","Yuan Plus"],
  Cadillac: ["ATS","BLS","CT4","CT5","CT6","CTS","DeVille","DTS","Escalade","Escalade ESV","Fleetwood","SRX","STS","XT4","XT5","XT6","XTS"],
  Changan: ["Alsvin","CS35","CS55","CS75","CS85","CS95","Eado","Hunter","Lamore","UNI-K","UNI-T","UNI-V"],
  Chery: ["Amulet","Arrizo 7","Arrizo 8","Bonus","CrossEastar","E5","Fora","Kimo","M11","QQ","Tiggo","Tiggo 2","Tiggo 3","Tiggo 4","Tiggo 5","Tiggo 7","Tiggo 8","Tiggo 8 Pro","Tiggo 8 Pro Max","Very"],
  Chevrolet: ["Alero","Astro","Avalanche","Aveo","Beretta","Blazer","Bolt","Camaro","Caprice","Captiva","Cavalier","Cobalt","Colorado","Corvette","Cruze","Epica","Equinox","Evanda","Express","HHR","Impala","Lacetti","Lanos","Malibu","Matiz","Monte Carlo","Niva","Orlando","Rezzo","Silverado","Spark","Suburban","Tahoe","Tracker","TrailBlazer","Trans Sport","Traverse","Trax","Uplander","Venture","Viva","Volt"],
  Chrysler: ["200","300C","300M","Aspen","Concorde","Crossfire","Grand Voyager","LeBaron","LHS","Neon","Pacifica","PT Cruiser","Sebring","Stratus","Town & Country","Voyager"],
  Citroen: ["Ami","AX","Berlingo","C-Crosser","C-Elysee","C-Zero","C1","C2","C3","C3 Aircross","C3 Picasso","C4","C4 Aircross","C4 Cactus","C4 Picasso","C4 SpaceTourer","C5","C5 Aircross","C5 X","C6","C8","DS3","DS4","DS5","Evasion","Grand C4 Picasso","Grand C4 SpaceTourer","Jumper","Jumpy","Nemo","Saxo","SpaceTourer","Xantia","XM","Xsara","Xsara Picasso","ZX"],
  Cupra: ["Ateca","Born","Formentor","Leon","Terramar"],
  Dacia: ["1300","1310","1325","1410","Dokker","Duster","Jogger","Lodgy","Logan","Logan MCV","Logan Pick-Up","Logan Van","Pick-Up","Sandero","Sandero Stepway","Solenza","Spring","SuperNova"],
  Daewoo: ["Espero","Evanda","Kalos","Lanos","Leganza","Magnus","Matiz","Nexia","Nubira","Rezzo","Sens","Tacuma"],
  DAF: ["CF","LF","XF"],
  Dodge: ["Avenger","Caliber","Caravan","Challenger","Charger","Dakota","Dart","Durango","Grand Caravan","Intrepid","Journey","Magnum","Neon","Nitro","Ram","Stealth","Stratus","Viper"],
  Dongfeng: ["AX7","Fengon 5","Fengon 7","Rich","Shine"],
  DS: ["3","4","5","7","9"],
  Fiat: ["124 Spider","500","500C","500L","500X","600","Albea","Barchetta","Brava","Bravo","Croma","Doblo","Ducato","Fiorino","Freemont","Fullback","Grande Punto","Idea","Linea","Marea","Multipla","Palio","Panda","Punto","Qubo","Scudo","Sedici","Seicento","Stilo","Strada","Talento","Tempra","Tipo","Ulysse","Uno"],
  Ford: ["Aerostar","B-Max","Bronco","Bronco Sport","C-Max","Capri","Cougar","Crown Victoria","EcoSport","Edge","Escape","Escort","Excursion","Expedition","Explorer","F-150","F-250","F-350","Fiesta","Flex","Focus","Fusion","Galaxy","Granada","Grand C-Max","GT","Ka","Kuga","Maverick","Mondeo","Mustang","Mustang Mach-E","Orion","Probe","Puma","Ranger","S-Max","Scorpio","Sierra","StreetKa","Taunus","Taurus","Thunderbird","Tourneo Connect","Tourneo Custom","Transit","Transit Connect","Transit Custom","Windstar"],
  Foton: ["Sauvana","Tunland","View"],
  GAC: ["Aion ES","Aion LX","Aion S","Aion V","Aion Y","Empow","GS3","GS4","GS5","GS8","M6","M8"],
  Geely: ["Atlas","Atlas Pro","CK","Coolray","Emgrand","Emgrand 7","Emgrand EC7","Emgrand GT","Emgrand X7","GC6","Geometry C","MK","Monjaro","Okavango","Preface","Tugella"],
  Genesis: ["G70","G80","G90","GV60","GV70","GV80"],
  GMC: ["Acadia","Canyon","Envoy","Jimmy","Safari","Savana","Sierra","Sonoma","Terrain","Yukon","Yukon XL"],
  "Great Wall": ["Cowry","Deer","Florid","Hover","Hover H3","Hover H5","Hover H6","Hover M2","Hover M4","Pegasus","Peri","Safe","Sailor","Sing","Socool","Wingle"],
  Haval: ["Dargo","F7","F7x","H2","H5","H6","H6 GT","H9","Jolion","M6","Third Generation H6"],
  Honda: ["Accord","Civic","Clarity","Concerto","CR-V","CR-Z","Crosstour","Element","Fit","FR-V","HR-V","Insight","Integra","Jazz","Legend","Logo","NSX","Odyssey","Pilot","Prelude","Ridgeline","S2000","Shuttle","Stream","ZR-V"],
  Hummer: ["H1","H2","H3"],
  Hyundai: ["Accent","Atos","Azera","Bayon","Coupe","Creta","Elantra","Equus","Galloper","Genesis","Getz","Grand Santa Fe","Grandeur","H-1","H-100","i10","i20","i30","i40","IONIQ","IONIQ 5","IONIQ 6","ix20","ix35","ix55","Kona","Lantra","Matrix","Palisade","Pony","Santa Cruz","Santa Fe","Santamo","Solaris","Sonata","Starex","Staria","Terracan","Tiburon","Trajet","Tucson","Veloster","Venue","Veracruz","XG"],
  Infiniti: ["EX","FX","G","I30","I35","JX","M","Q30","Q45","Q50","Q60","Q70","QX30","QX4","QX50","QX55","QX56","QX60","QX70","QX80"],
  Isuzu: ["Amigo","Ascender","Axiom","Campo","D-Max","Gemini","Midi","MU","MU-X","Piazza","Rodeo","Trooper","VehiCross"],
  Iveco: ["Daily","EuroCargo","Massif"],
  JAC: ["J7","JS4","JS6","S3","S5","S7","T6","T8"],
  Jaecoo: ["J7","J8"],
  Jaguar: ["E-Pace","F-Pace","F-Type","I-Pace","S-Type","X-Type","XE","XF","XJ","XJR","XJS","XK","XKR"],
  Jeep: ["Cherokee","Commander","Compass","Gladiator","Grand Cherokee","Grand Cherokee L","Grand Wagoneer","Liberty","Patriot","Renegade","Wagoneer","Wrangler"],
  Jetour: ["Dashing","T2","X70","X70 Plus","X90","X90 Plus"],
  Kia: ["Avella","Besta","Cadenza","Carens","Carnival","Ceed","Cerato","Clarus","EV6","EV9","Forte","K5","K900","Magentis","Mohave","Niro","Opirus","Optima","Picanto","Pregio","Pride","ProCeed","Quoris","Ray","Rio","Sedona","Seltos","Sephia","Shuma","Sorento","Soul","Spectra","Sportage","Stinger","Stonic","Telluride","Venga","XCeed"],
  Lada: ["110","111","112","2101","2104","2105","2106","2107","2108","2109","21099","2110","2111","2112","2113","2114","2115","Granta","Kalina","Largus","Niva","Niva Legend","Priora","Vesta","XRAY"],
  Lancia: ["Dedra","Delta","Kappa","Lybra","Musa","Phedra","Thema","Thesis","Ypsilon","Zeta"],
  "Land Rover": ["Defender","Discovery","Discovery Sport","Freelander","Range Rover","Range Rover Evoque","Range Rover Sport","Range Rover Velar","Series III"],
  Lexus: ["CT","ES","GS","GX","HS","IS","LC","LFA","LM","LS","LX","NX","RC","RC F","RX","RZ","SC","UX"],
  "Li Auto": ["L6","L7","L8","L9","Mega","One"],
  Lifan: ["320","520","620","820","Myway","Smily","Solano","X50","X60","X70"],
  Lincoln: ["Aviator","Continental","Corsair","LS","Mark LT","MKC","MKS","MKT","MKX","MKZ","Nautilus","Navigator","Town Car"],
  Lotus: ["Elise","Emira","Evora","Exige"],
  Lucid: ["Air","Gravity"],
  MAN: ["TGE","TGL","TGM","TGS","TGX"],
  Maserati: ["3200 GT","Coupe","Ghibli","GranCabrio","GranTurismo","Grecale","Levante","MC20","Quattroporte","Spyder"],
  Mazda: ["121","2","3","323","5","6","626","929","B-Series","BT-50","CX-3","CX-30","CX-5","CX-50","CX-60","CX-7","CX-9","CX-90","Demio","MPV","MX-3","MX-30","MX-5","MX-6","Premacy","Protege","RX-7","RX-8","Tribute","Xedos"],
  "Mercedes-Benz": ["190","A-Class","AMG GT","B-Class","C-Class","Citan","CL","CLA","CLC","CLK","CLS","E-Class","EQA","EQB","EQC","EQE","EQS","EQV","G-Class","GL","GLA","GLB","GLC","GLE","GLK","GLS","M-Class","Maybach S-Class","R-Class","S-Class","SL","SLC","SLK","SLR McLaren","SLS AMG","Sprinter","V-Class","Vaneo","Viano","Vito","X-Class"],
  MG: ["3","350","5","550","6","750","HS","Marvel R","TF","ZS","ZS EV","ZST"],
  Mini: ["Clubman","Cooper","Cooper S","Countryman","Coupe","One","Paceman","Roadster"],
  Mitsubishi: ["3000 GT","ASX","Carisma","Colt","Diamante","Eclipse","Eclipse Cross","Endeavor","Galant","Grandis","i-MiEV","L200","Lancer","Mirage","Montero","Montero Sport","Outlander","Outlander Sport","Pajero","Pajero Pinin","Pajero Sport","RVR","Sigma","Space Gear","Space Runner","Space Star","Space Wagon"],
  NIO: ["EC6","EC7","EL6","EL7","EL8","ES6","ES7","ES8","ET5","ET7"],
  Nissan: ["100NX","200SX","350Z","370Z","Almera","Almera Classic","Almera Tino","Altima","Ariya","Armada","Bluebird","Cube","Frontier","GT-R","Juke","Kicks","Leaf","Maxima","Micra","Murano","Navara","Note","NP300","NV","Pathfinder","Patrol","Pixo","Primera","Pulsar","Qashqai","Quest","Rogue","Sentra","Serena","Silvia","Skyline","Sunny","Teana","Terrano","Tiida","Titan","Townstar","Versa","X-Trail","Xterra","Z"],
  Omoda: ["C5","S5"],
  Opel: ["Adam","Agila","Ampera","Antara","Ascona","Astra","Calibra","Campo","Cascada","Combo","Commodore","Corsa","Crossland","Crossland X","Frontera","Grandland","Grandland X","GT","Insignia","Kadett","Meriva","Mokka","Mokka X","Monterey","Monza","Movano","Omega","Rekord","Senator","Signum","Sintra","Speedster","Tigra","Vectra","Vita","Vivaro","Zafira","Zafira Life"],
  Peugeot: ["1007","106","107","108","2008","205","206","207","208","3008","301","305","306","307","308","4007","4008","405","406","407","408","5008","504","505","508","604","605","607","806","807","Bipper","Boxer","Expert","Partner","RCZ","Rifter","Traveller"],
  Polestar: ["1","2","3","4"],
  Porsche: ["718 Boxster","718 Cayman","911","918 Spyder","924","928","944","968","Boxster","Carrera GT","Cayenne","Cayman","Macan","Panamera","Taycan"],
  Ram: ["1500","2500","3500","ProMaster"],
  Ravon: ["Gentra","Matiz","Nexia R3","R2","R4"],
  Renault: ["11","12","14","15","16","17","18","19","20","21","25","30","4","5","9","Arkana","Austral","Avantime","Captur","Clio","Dokker","Duster","Espace","Express","Fluence","Fuego","Grand Espace","Grand Scenic","Kadjar","Kangoo","Koleos","Laguna","Latitude","Logan","Master","Megane","Modus","Rafale","Safrane","Scenic","Scenic Conquest","Symbol","Talisman","Trafic","Twingo","Twizy","Vel Satis","Wind","Zoe"],
  Rivian: ["R1S","R1T"],
  Rover: ["200","214","216","218","220","25","400","414","416","418","420","45","600","618","620","623","75","800","820","825","827","CityRover","Streetwise"],
  Saab: ["9-3","9-4X","9-5","9-7X","900","9000"],
  Scania: ["G-series","P-series","R-series","S-series"],
  Seat: ["Alhambra","Altea","Altea XL","Arona","Arosa","Ateca","Cordoba","Exeo","Ibiza","Inca","Leon","Malaga","Marbella","Mii","Tarraco","Terra","Toledo"],
  Skoda: ["100","105","120","130","135","136","Citigo","Enyaq","Fabia","Favorit","Felicia","Forman","Kamiq","Karoq","Kodiaq","Octavia","Praktik","Rapid","Roomster","Scala","Superb","Yeti"],
  Skywell: ["ET5","HT-i"],
  Smart: ["#1","#3","Forfour","Fortwo","Roadster"],
  SsangYong: ["Actyon","Actyon Sports","Chairman","Korando","Kyron","Musso","Rexton","Rodius","Stavic","Tivoli","Torres","XLV"],
  Subaru: ["Ascent","Baja","BRZ","Crosstrek","Forester","Impreza","Justy","Legacy","Levorg","Libero","Outback","Solterra","SVX","Tribeca","WRX","XV"],
  Suzuki: ["Alto","Baleno","Celerio","Grand Vitara","Ignis","Jimny","Kizashi","Liana","Samurai","Splash","Swace","Swift","SX4","Vitara","Wagon R","XL7"],
  Tesla: ["Cybertruck","Model 3","Model S","Model X","Model Y","Roadster"],
  Toyota: ["4Runner","Alphard","Auris","Avalon","Avensis","Avensis Verso","Aygo","bZ4X","C-HR","Camry","Carina","Celica","Corolla","Corolla Cross","Corolla Verso","Crown","FJ Cruiser","Fortuner","GR86","GT86","Highlander","Hilux","Land Cruiser","Land Cruiser Prado","Matrix","Mirai","MR2","Paseo","Picnic","Previa","Prius","Proace","RAV4","Sequoia","Sienna","Starlet","Supra","Tacoma","Tercel","Tundra","Urban Cruiser","Venza","Verso","Yaris","Yaris Cross"],
  Volkswagen: ["Amarok","Arteon","Atlas","Beetle","Bora","Caddy","Corrado","Crafter","Cross Golf","Cross Touran","Eos","Fox","Golf","Golf Alltrack","Golf GTE","Golf Plus","Golf Sportsvan","ID.3","ID.4","ID.5","ID.6","ID.7","ID.Buzz","Jetta","Lupo","Multivan","New Beetle","Passat","Passat Alltrack","Passat CC","Phaeton","Polo","Routan","Scirocco","Sharan","T-Cross","T-Roc","Taigo","Tayron","Teramont","Tiguan","Tiguan Allspace","Touareg","Touran","Transporter","Up","Vento","Virtus"],
  Volvo: ["240","340","440","460","480","740","760","850","940","960","C30","C40","C70","EX30","EX90","S40","S60","S70","S80","S90","V40","V50","V60","V70","V90","XC40","XC60","XC70","XC90"],
  XPeng: ["G3","G6","G9","P5","P7"],
  ZAZ: ["1102","1103","1105","965","966","968","Chance","Forza","Lanos","Sens","Vida"],
  Zeekr: ["001","007","009","X"],
};

export const BRANDS: string[] = Object.keys(BRAND_MODELS).sort((a, b) => a.localeCompare(b, "uk"));

export function getModelsForBrand(brand: string): string[] {
  return [...(BRAND_MODELS[brand] ?? [])];
}

export function filterOptions(options: string[], query: string, limit = 80): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return options.slice(0, limit);
  return options.filter(o => o.toLowerCase().includes(q)).slice(0, limit);
}

export const TOTAL_BRANDS = 87;
export const TOTAL_MODELS = 1425;
