/** Мапінг марок FE → файли в /public/brands (svg або png). */

const BRAND_ICON_EXT: Record<string, "svg" | "png"> = {
  buick: "png",
  cadillac: "png",
  changan: "png",
  chery: "png",
  chevrolet: "png",
  daewoo: "png",
  dodge: "png",
  dongfeng: "png",
  ford: "png",
  foton: "png",
  gac: "png",
  gmc: "png",
  "great-wall": "png",
  haval: "png",
  honda: "png",
  jac: "png",
  lancia: "png",
  "li-auto": "png",
  lifan: "png",
  lucid: "png",
  maserati: "png",
  mg: "png",
  nio: "png",
  omoda: "png",
  polestar: "png",
  rover: "png",
  saab: "png",
  smart: "png",
  ssangyong: "png",
  subaru: "png",
  xpeng: "png",
  zaz: "png",
  zeekr: "png",
};

/** Slug-и з наявними файлами в public/brands */
const BRAND_ICON_SLUGS = new Set([
  "acura",
  "alfa-romeo",
  "aston-martin",
  "audi",
  "baic",
  "bentley",
  "bmw",
  "buick",
  "byd",
  "cadillac",
  "changan",
  "chery",
  "chevrolet",
  "chrysler",
  "citroen",
  "cupra",
  "dacia",
  "daewoo",
  "daf",
  "dodge",
  "dongfeng",
  "ds",
  "ducati",
  "fiat",
  "ford",
  "foton",
  "gac",
  "geely",
  "genesis",
  "gmc",
  "great-wall",
  "harley-davidson",
  "haval",
  "honda",
  "hummer",
  "hyundai",
  "indian",
  "infiniti",
  "isuzu",
  "iveco",
  "jac",
  "jaecoo",
  "jaguar",
  "jeep",
  "jetour",
  "kawasaki",
  "kia",
  "ktm",
  "lada",
  "lancia",
  "land-rover",
  "lexus",
  "li-auto",
  "lifan",
  "lincoln",
  "lotus",
  "lucid",
  "man",
  "maserati",
  "mazda",
  "mercedes-benz",
  "mg",
  "mini",
  "mitsubishi",
  "nio",
  "nissan",
  "omoda",
  "opel",
  "peugeot",
  "polestar",
  "porsche",
  "ram",
  "ravon",
  "renault",
  "renault-trucks",
  "rivian",
  "rover",
  "saab",
  "scania",
  "seat",
  "skoda",
  "skywell",
  "smart",
  "ssangyong",
  "subaru",
  "suzuki",
  "tesla",
  "toyota",
  "triumph",
  "volkswagen",
  "volvo",
  "xpeng",
  "yamaha",
  "zaz",
  "zeekr",
]);

export function brandNameToIconSlug(brand: string): string {
  return brand
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** URL іконки марки або null, якщо файлу немає в public/brands. */
export function getBrandIconUrl(brand: string): string | null {
  if (!brand.trim()) return null;
  const slug = brandNameToIconSlug(brand);
  if (!BRAND_ICON_SLUGS.has(slug)) return null;
  const ext = BRAND_ICON_EXT[slug] ?? "svg";
  return `/brands/${slug}.${ext}`;
}

export function hasBrandIcon(brand: string): boolean {
  return BRAND_ICON_SLUGS.has(brandNameToIconSlug(brand));
}
